spring:
  application:
    name: eureka-server
  output:
    ansi:
      enabled: always
server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
logging:
  pattern:
    console: "[%clr(%5p)] - %clr(%m){magenta} %n"

